CREATE TABLE restaurants (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UUID BINARY(16) NOT NULL UNIQUE,
    RESTAURANT_NAME VARCHAR(30) NOT NULL,
    FULL_ADRESS VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT DATETIME DEFAULT NULL
);

