CREATE TABLE products (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UUID BINARY(16) NOT NULL UNIQUE,
    CATEGORY_ID INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT DATETIME DEFAULT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES product_categories(ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES restaurants(ID)
);