CREATE TABLE product_sales (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UUID BINARY(16) NOT NULL UNIQUE,
    PRODUCT_ID INT NOT NULL,
    DESCRIPTION VARCHAR(30),
    PROMOTIONAL_PRICE DECIMAL(10,2) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT DATETIME DEFAULT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID)
);